import '../styles/globals.css'

import { AppProps } from 'next/app';
import { Analytics } from '@vercel/analytics/react';
import Header from '../components/layout/Header';
import Head from 'next/head';

function App({ Component, pageProps }: AppProps) {
  return (
    <div className="max-w-lg mx-auto pb-4 bg-slate-100 min-h-screen">
      <Head>
        <meta property="og:title" content="Moodify - Personalize songs for your current mood" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="" />
        <meta property="og:url" content="https://moodify-songs.vercel.app/" />
        <meta name="twitter:card" content="summary_large_image" />

        <meta property="og:description" content="Spotify playlist generated by your mood" />
        <meta property="og:site_name" content="Moodify" />
        <meta name="twitter:image:alt" content="Spotify playlist generated by your mood" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <Analytics />
    </div>
  );

}

export default App;
